# Generated by Django 5.1.3 on 2024-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.DateField(auto_now_add=True)),
                ('pages', models.IntegerField()),
                ('janri', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='photos/')),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
