# Generated by Django 5.1.3 on 2024-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vazifa_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='vazifa',
            options={'verbose_name': 'Vazifa', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AddField(
            model_name='book',
            name='mualif',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
    ]
